name: Build and Deploy Global HQ Admin

on:
  push:
    branches: [ dev, staging, main ]
    paths:
      - 'social-commerce/global-hq-admin/**'
  pull_request:
    branches: [ dev, staging, main ]
    paths:
      - 'social-commerce/global-hq-admin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: social-commerce/global-hq-admin/package.json
    
    - name: Install dependencies
      working-directory: social-commerce/global-hq-admin
      run: |
        npm install
        
    - name: Run tests
      working-directory: social-commerce/global-hq-admin
      run: |
        npm run test -- --coverage --watchAll=false
        
    - name: Build React app
      working-directory: social-commerce/global-hq-admin
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'https://api-dev.gogidix-ecosystem.com' }}
        REACT_APP_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'development' }}
      run: |
        npm run build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: global-hq-admin-build
        path: social-commerce/global-hq-admin/build/
        retention-days: 30