apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  namespace: social-commerce
  labels:
    app: marketplace
    domain: social-commerce
spec:
  selector:
    app: marketplace
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
