apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: social-media-integration-hpa
  namespace: social-commerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-media-integration
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
