apiVersion: v1
kind: Service
metadata:
  name: regional-admin-service
  namespace: social-commerce
  labels:
    app: regional-admin
    domain: social-commerce
spec:
  selector:
    app: regional-admin
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
