apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  namespace: social-commerce
  labels:
    app: order-service
    domain: social-commerce
spec:
  selector:
    app: order-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
