apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: global-hq-admin-hpa
  namespace: social-commerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: global-hq-admin
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
