apiVersion: v1
kind: Service
metadata:
  name: global-hq-admin-service
  namespace: social-commerce
  labels:
    app: global-hq-admin
    domain: social-commerce
spec:
  selector:
    app: global-hq-admin
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
