apiVersion: v1
kind: Service
metadata:
  name: integration-performance-service
  namespace: social-commerce
  labels:
    app: integration-performance
    domain: social-commerce
spec:
  selector:
    app: integration-performance
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
