apiVersion: v1
kind: Service
metadata:
  name: social-commerce-shared-service
  namespace: social-commerce
  labels:
    app: social-commerce-shared
    domain: social-commerce
spec:
  selector:
    app: social-commerce-shared
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
