apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulfillment-options
  namespace: social-commerce
  labels:
    app: fulfillment-options
    domain: social-commerce
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fulfillment-options
  template:
    metadata:
      labels:
        app: fulfillment-options
        domain: social-commerce
        tier: backend
    spec:
      containers:
      - name: fulfillment-options
        image: ${DOCKER_REGISTRY}/fulfillment-options:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: fulfillment-options-db-secret
              key: database-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: fulfillment-options-db-secret
              key: database-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fulfillment-options-db-secret
              key: database-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: fulfillment-options-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fulfillment-options-config
  namespace: social-commerce
data:
  application-kubernetes.yml: |
    server:
      port: 8080
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.exalt: INFO
        org.springframework: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
---
apiVersion: v1
kind: Secret
metadata:
  name: fulfillment-options-db-secret
  namespace: social-commerce
type: Opaque
data:
  database-url: ${DATABASE_URL_BASE64}
  database-username: ${DATABASE_USERNAME_BASE64}
  database-password: ${DATABASE_PASSWORD_BASE64}
