apiVersion: v1
kind: Service
metadata:
  name: fulfillment-options-service
  namespace: social-commerce
  labels:
    app: fulfillment-options
    domain: social-commerce
spec:
  selector:
    app: fulfillment-options
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
