apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: social-commerce-kafka
  namespace: social-commerce
spec:
  kafka:
    version: 3.3.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
      auto.create.topics.enable: false
      message.max.bytes: 1000000
      replica.fetch.max.bytes: 1000000
      log.retention.hours: 24
      log.segment.bytes: 1073741824
      num.network.threads: 8
      num.io.threads: 16
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: "fast-ssd"
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    jvmOptions:
      -Xms: 2048m
      -Xmx: 2048m
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: "fast-ssd"
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: social-commerce-connect
  namespace: social-commerce
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.3.0
  replicas: 2
  bootstrapServers: social-commerce-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: social-commerce-kafka-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
  build:
    output:
      type: docker
      image: social-commerce/kafka-connect:latest
    plugins:
      - name: mongodb-connector
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            artifact: io.confluent:kafka-connect-mongodb:1.3.1
      - name: elasticsearch-connector
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            artifact: io.confluent:kafka-connect-elasticsearch:11.0.0
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: order-placed-event
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 86400000  # 24 hours
    segment.ms: 3600000     # 1 hour
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: payment-completed-event
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 432000000  # 5 days
    segment.ms: 3600000      # 1 hour
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: product-stock-updated-event
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 86400000  # 24 hours
    segment.ms: 1800000     # 30 minutes
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: commission-calculated-event
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 2592000000  # 30 days
    segment.ms: 3600000       # 1 hour
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: analytics-engagement-event
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 9
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    segment.ms: 1800000      # 30 minutes
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: dead-letter-topic
  namespace: social-commerce
  labels:
    strimzi.io/cluster: social-commerce-kafka
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 2592000000  # 30 days
    segment.ms: 3600000       # 1 hour
    cleanup.policy: delete
