spring:
  application:
    name: customer-support-service
  
  cloud:
    config:
      enabled: false
  
  eureka:
    client:
      enabled: false

server:
  port: 8095

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics