apiVersion: v1
kind: Service
metadata:
  name: admin-interfaces-service
  namespace: social-commerce
  labels:
    app: admin-interfaces
    domain: social-commerce
spec:
  selector:
    app: admin-interfaces
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
