apiVersion: v1
kind: Service
metadata:
  name: user-web-app-service
  namespace: social-commerce
  labels:
    app: user-web-app
    domain: social-commerce
spec:
  selector:
    app: user-web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
