apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: social-commerce
  labels:
    app: api-gateway
    domain: social-commerce
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
