apiVersion: v1
kind: Service
metadata:
  name: localization-service-service
  namespace: social-commerce
  labels:
    app: localization-service
    domain: social-commerce
spec:
  selector:
    app: localization-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
