spring:
  application:
    name: regional-admin-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

server:
  port: ${SERVER_PORT:8087}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    enabled: ${EUREKA_ENABLED:true}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.exalt.socialcommerce: ${LOG_LEVEL:INFO}
