apiVersion: v1
kind: Service
metadata:
  name: integration-optimization-service
  namespace: social-commerce
  labels:
    app: integration-optimization
    domain: social-commerce
spec:
  selector:
    app: integration-optimization
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
